[tool.poetry]
name = "example_satellite"
version = "0.1.0"
description = ""
authors = ["Ray Yamamoto Hilton <ray@wirestorm.net>"]

[tool.poetry.dependencies]
python = "^3.9"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.2.0"]
build-backend = "poetry.core.masonry.api"
